import { HttpError, fetchFilteredJobs } from "../_lib/filter.mjs";
import { listSubscriptions } from "../_lib/alerts.mjs";

const MAX_PER_DIGEST = 6;

function sendEmail({ to, subject, html }) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.DIGEST_FROM;
  if (!apiKey || !from) {
    throw new HttpError(
      500,
      "Email isn't configured yet. Add RESEND_API_KEY and DIGEST_FROM on Vercel to send digests.",
      "missing_config"
    );
  }

  return fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({ from, to, subject, html }),
  }).then(async (res) => {
    const data = await res.json().catch(() => ({}));
    if (!res.ok) {
      throw new HttpError(502, `Email provider error: ${data.message || `HTTP ${res.status}`}.`, "upstream");
    }
    return data;
  });
}

function buildDigestHtml(sub, jobs) {
  const rows = jobs
    .slice(0, MAX_PER_DIGEST)
    .map(
      (job) => `
        <li style="margin-bottom:18px;list-style:none;border-bottom:1px solid #e2e8f0;padding-bottom:14px;">
          <a href="${job.url}" style="font-size:16px;font-weight:700;color:#4f46e5;text-decoration:none;">${job.title}</a>
          <div style="color:#64748b;font-size:14px;margin:2px 0 6px;">${job.company_name} &middot; ${(job.location || []).join(", ") || (job.remote ? "Remote" : "Not stated")}</div>
          <div style="color:#334155;font-size:13px;">${(job.tags || []).slice(0, 8).join(", ")}</div>
        </li>`
    )
    .join("");

  const city = sub.city ? ` in ${sub.city}` : "";
  const search = [sub.targetRole, sub.skills].filter(Boolean).join(" · ");

  return `
    <div style="font-family:system-ui,Arial,sans-serif;max-width:600px;margin:0 auto;padding:24px;">
      <h2 style="margin:0 0 4px;">Your daily job matches 📌</h2>
      <p style="color:#64748b;margin:0 0 20px;">Search: <strong>${search}</strong>${city} — ${jobs.length} new-ish matches today.</p>
      <ul style="margin:0;padding:0;">${rows}</ul>
      <p style="color:#64748b;font-size:12px;margin-top:24px;">Generated by My Job Matcher · Jobs from <a href="https://www.arbeitnow.com" style="color:#4f46e5;">Arbeitnow</a>. To stop alerts, reply or manage in the app.</p>
    </div>`;
}

function isAuthorized(req) {
  const cronSecret = process.env.CRON_SECRET;
  if (req.headers["x-vercel-cron"]) return true;
  if (cronSecret) {
    const auth = req.headers.authorization || "";
    return auth === `Bearer ${cronSecret}`;
  }
  return true;
}

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  if (req.method === "OPTIONS") return res.status(204).end();
  if (req.method !== "POST") {
    return res.status(405).json({ error: "This endpoint accepts POST requests only.", code: "method" });
  }

  if (!isAuthorized(req)) {
    return res.status(401).json({ error: "Unauthorized.", code: "unauthorized" });
  }

  try {
    const subs = await listSubscriptions();
    const summary = { checked: subs.length, sent: 0, skipped: 0, errors: [] };

    for (const sub of subs) {
      try {
        const { jobs } = await fetchFilteredJobs(sub);
        if (!jobs.length) {
          summary.skipped += 1;
          continue;
        }
        await sendEmail({
          to: sub.email,
          subject: `My Job Matcher: ${jobs.length} neue Matches${sub.city ? ` in ${sub.city}` : ""}`,
          html: buildDigestHtml(sub, jobs),
        });
        summary.sent += 1;
      } catch (err) {
        summary.errors.push({ email: sub.email, message: err.message });
      }
    }

    return res.status(200).json({ ok: true, ...summary });
  } catch (err) {
    if (err instanceof HttpError) {
      return res.status(err.status).json({ error: err.message, code: err.code });
    }
    console.error("[/api/cron/digest] unexpected:", err);
    return res.status(500).json({
      error: "Something went wrong on our end. Please try again in a moment.",
      code: "internal",
    });
  }
}
